Repository The-Standard-Organization/STX.SPAL.Core, pull requests merged in 2024-06, with the labels that each got.

#16 DOCUMENTATION: Readme Add New Acknowledgements
  README.md
Labels: DOCUMENTATION

#17 BROKERS: Add DependencyInjectionBroker #9
  STX.SPAL.Core/Brokers/DependenciesInjection/DependencyInjectionBroker.ServiceCollection.cs
  STX.SPAL.Core/Brokers/DependenciesInjection/DependencyInjectionBroker.ServiceProvider.cs
  STX.SPAL.Core/Brokers/DependenciesInjection/DependencyInjectionBroker.cs
  STX.SPAL.Core/Brokers/DependenciesInjection/IDependencyInjectionBroker.ServiceCollection.cs
  STX.SPAL.Core/Brokers/DependenciesInjection/IDependencyInjectionBroker.ServiceProvider.cs
  STX.SPAL.Core/Brokers/DependenciesInjection/IDependencyInjectionBroker.cs
  STX.SPAL.Core/STX.SPAL.Core.csproj
Labels: BROKERS

#21 CONFIG: Update Label Script Yaml
  .github/workflows/build.yml
Labels: CONFIG

#23 MINOR FIX: Fix localized external exceptions inside TryCatch
  STX.SPAL.Core/Services/Foundations/Assemblies/AssemblyService.Exceptions.cs
Labels: MINOR FIX
